### ISSUE TITLE
Automatically Build New Releases

### ISSUE THREAD

**Issue by hackel** [Spirotot/timew-spirotot#1]
Any chance you could update this to track Github instead of taskwarrior.org?  Version 1.1.1 was released last month, but it's not on the TaskWarrior website yet for some reason.
https://github.com/GothenburgBitFactory/timewarrior/releases/tag/v1.1.1

**Comment by Spirotot** [comment]
I'll look into it. I think they (Gothenburg/Timewarrior) would actually have to be the one integrating the auto-builds. That's why I've left my Snap named "timew-spirotot" -- IMO, the "timew" title (sans username) should belong to them.

You should file an Issue requesting Snapcraft support on their repo if you haven't already! And/or I will see about making a pull request to merge in the YAML from this project.

FWIW, I did push a new v1.1.1 to stable today.
